stages:
  - build

variables:
  APT_UPDATE: apt-get update -qq -y
  APT_INSTALL: apt-get install -qq -y
  DISABLE_CLANG_FORMAT: "true"

build:gcc:
  stage: build
  tags:
    - ubuntu
    - docker
  script:
    - $APT_UPDATE && $APT_INSTALL cmake python3 gcc-8 g++-8 ninja-build > /dev/null
    - cd build
    - CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 TARGET=Ninja ./configure.sh
    - cd ../out/x64
    - ninja

build:clang:
  stage: build
  tags:
    - ubuntu
    - docker
  script:
    - $APT_UPDATE && $APT_INSTALL cmake python3 clang-7 clang-tidy-7 ninja-build > /dev/null
    - cd build
    - CC=/usr/bin/clang-7 CXX=/usr/bin/clang++-7 TARGET=Ninja ./configure.sh
    - cd ../out/x64
    - ninja
