stages:
  - build

variables:
  APT_UPDATE: apt-get update -qq -y
  APT_INSTALL: apt-get install -qq -y
  DISABLE_CLANG_FORMAT: "true"

build:gcc:
  stage: build
  tags:
    - ubuntu
    - docker
  script:
    - $APT_UPDATE && $APT_INSTALL cmake python3 gcc-8 g++-8 ninja-build > /dev/null
    - cd build
    - CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 TARGET=Ninja ./configure.sh
    - cd ../out/x64
    - ninja

build:clang:
  stage: build
  tags:
    - ubuntu
    - docker
  script:
    - $APT_UPDATE && $APT_INSTALL cmake python3 clang-7 clang-tidy-7 ninja-build > /dev/null
    - cd build
    - CC=/usr/bin/clang-7 CXX=/usr/bin/clang++-7 TARGET=Ninja USE_STATIC_ANALYZER=1 ./configure.sh
    - cd ../out/x64
    - ninja

build:msvc:
  stage: build
  tags:
    - msvc2017
  script:
    - mkdir out\x64
    - cd out/x64
    - cmake ../../build -G "Visual Studio 15 2017 Win64" -DCMAKE_CONFIGURATION_TYPES=RelWithDebInfo
    - cmake --build . --config RelWithDebInfo -- -verbosity:minimal
