language: cpp

linux-build: &linux-build
  dist: bionic
  script:
    - cd build
    - ./configure.sh
    - cd ../out/x64
    - make

matrix:
    include:
        - name: gcc linux
          compiler: gcc
          <<: *linux-build
        - name: clang linux
          compiler: clang
          <<: *linux-build
        - name: clang linux with static analysis
          compiler: clang
          env: USE_STATIC_ANALYZER=1
          <<: *linux-build
        - name: visual studio 2017 windows
          os: windows
          before_install:
            - choco install python
          script:
            - cd build
            - ./configure_2017.cmd
            - cd ../out/x64
            - cmake --build . --config RelWithDebInfo -- -verbosity:minimal
